openapi: 3.0.2
info:
  title: SUIT
  version: 1.0.0
servers:
  - url: https://localhost:8000
paths:
  /register:
    post:
      tags:
        - Users & Staff
      summary: User registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullname:
                  type: string
                username:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                phone_number:
                  type: string
                gender:
                  type: string
                  enum: [male, female]
                address:
                  type: string
      responses:
        '201':
          $ref: "#/components/responses/ResponseCreateUser"
        '400':
          $ref: "#/components/responses/BadRequest"
        '500':
          $ref: "#/components/responses/ServerError"
  
  /registerstaff:
    post:
      tags:
        - Users & Staff
      summary: Register Staff
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullname:
                  type: string
                username:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                phone_number:
                  type: string
                drop_point_id:
                  type: number
      responses:
        '200':
          $ref: "#/components/responses/ResponseCreateStaff"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '500':
          $ref: "#/components/responses/ServerError"
  
  /login:
    post:
      tags:
        - Users & Staff
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          $ref: "#/components/responses/ResponseLoginUser"
        '400':
          $ref: "#/components/responses/BadRequest"
        '500':
          $ref: "#/components/responses/ServerError"

  /profile:
    get:
      security:
        - bearerAuth: []
      tags:
        - Users & Staff
      summary: Get current login user data
      responses:
        '200':
          $ref: "#/components/responses/ResponseGetProfile"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '500':
          $ref: "#/components/responses/ServerError"   
    put:
      security:
        - bearerAuth: []
      tags:
        - Users & Staff
      summary: Edit current login user data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullname:
                  type: string
                username:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                phone_number:
                  type: string
                gender:
                  type: string
                  enum: [male, female]
                address:
                  type: string
      responses:
        '200':
          $ref: "#/components/responses/ResponseEditUser"
        '400':
          $ref: "#/components/responses/BadRequest"
        '500':
          $ref: "#/components/responses/ServerError" 
  
  /users:
    get:
      security:
        - bearerAuth: []
      tags:
        - Users & Staff
      summary: Get all users (staff only)
      responses:
        '200':
          $ref: "#/components/responses/ResponseGetAllUsers"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '500':
          $ref: "#/components/responses/ServerError"

  /staff:
    get:
      security:
        - bearerAuth: []
      tags:
        - Users & Staff
      summary: Get all Staff (staff only)
      responses:
        '200':
          $ref: "#/components/responses/ResponseGetAllStaff"
        '400':
          $ref: "#/components/responses/BadRequest"
        '500':
          $ref: "#/components/responses/ServerError"
  
  /droppoints:
    get:
      tags:
        - Drop Points
      summary: Get all drop points
      responses:
        '200':
          $ref: "#/components/responses/ResponseGetAllDropPoint"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '500':
          $ref: "#/components/responses/ServerError"
    post:
      security:
        - bearerAuth: []
      tags:
        - Drop Points
      summary: Add drop points (staff only)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
      responses:
        '201':
          $ref: "#/components/responses/ResponseCreateDropPoint"
        '400':
          $ref: "#/components/responses/BadRequest"
        '500':
          $ref: "#/components/responses/ServerError" 
                  
  /droppoints/{id}:
    put:
      security:
        - bearerAuth: []
      tags:
        - Drop Points
      summary: Edit drop points by id (staff only)
      parameters:
        - name: id
          in: path
          required: true
          description: id for edit specific drop point
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
      responses:
        '200':
          $ref: "#/components/responses/ResponseEditDropPoint"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '404':
          $ref: "#/components/responses/NotFound"
        '500':
          $ref: "#/components/responses/ServerError" 
    delete:
      security:
        - bearerAuth: []
      tags:
        - Drop Points
      summary: Delete drop points by id (staff only)
      parameters:
        - name: id
          in: path
          required: true
          description: id for delete specific drop point
          schema:
            type: number
      responses:
        '200':
          $ref: "#/components/responses/ResponseDeleteDropPoint"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '404':
          $ref: "#/components/responses/NotFound"
        '500':
          $ref: "#/components/responses/ServerError"
          
  /categories:
    get:
      tags:
        - Categories
      summary: Get all categories
      responses:
        '200':
          $ref: "#/components/responses/ResponseGetAllCategories"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '500':
          $ref: "#/components/responses/ServerError"
    post:
      security:
        - bearerAuth: []
      tags:
        - Categories
      summary: Add categories (staff only)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                point:
                  type: number
      responses:
        '201':
          $ref: "#/components/responses/ResponseCreateCategory"
        '400':
          $ref: "#/components/responses/BadRequest"
        '500':
          $ref: "#/components/responses/ServerError" 
                  
  /categories/{id}:
    put:
      security:
        - bearerAuth: []
      tags:
        - Categories
      summary: Edit category by id (staff only)
      parameters:
        - name: id
          in: path
          required: true
          description: id for edit specific category
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                point:
                  type: number
      responses:
        '200':
          $ref: "#/components/responses/ResponseEditCategory"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '404':
          $ref: "#/components/responses/NotFound"
        '500':
          $ref: "#/components/responses/ServerError" 
    delete:
      security:
        - bearerAuth: []
      tags:
        - Categories
      summary: Delete category by id (staff only)
      parameters:
        - name: id
          in: path
          required: true
          description: id for delete specific category
          schema:
            type: number
      responses:
        '200':
          $ref: "#/components/responses/ResponseDeleteCategory"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '404':
          $ref: "#/components/responses/NotFound"
        '500':
          $ref: "#/components/responses/ServerError" 

  /vouchers:
    get:
      tags:
        - Vouchers
      summary: Get all vouchers
      responses:
        '200':
          $ref: "#/components/responses/ResponseGetAllVouchers"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '500':
          $ref: "#/components/responses/ServerError"
    post:
      security:
        - bearerAuth: []
      tags:
        - Vouchers
      summary: Add vouchers (staff only)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                point:
                  type: number
      responses:
        '201':
          $ref: "#/components/responses/ResponseCreateVoucher"
        '400':
          $ref: "#/components/responses/BadRequest"
        '500':
          $ref: "#/components/responses/ServerError" 
                  
  /vouchers/{id}:
    put:
      security:
        - bearerAuth: []
      tags:
        - Vouchers
      summary: Edit vouchers by id (staff only)
      parameters:
        - name: id
          in: path
          required: true
          description: id for edit specific vouchers
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                point:
                  type: number
      responses:
        '200':
          $ref: "#/components/responses/ResponseEditVoucher"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '404':
          $ref: "#/components/responses/NotFound"
        '500':
          $ref: "#/components/responses/ServerError" 
    delete:
      security:
        - bearerAuth: []
      tags:
        - Vouchers
      summary: Delete vouchers by id (staff only)
      parameters:
        - name: id
          in: path
          required: true
          description: id for delete specific vouchers
          schema:
            type: number
      responses:
        '200':
          $ref: "#/components/responses/ResponseDeleteVoucher"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '404':
          $ref: "#/components/responses/NotFound"
        '500':
          $ref: "#/components/responses/ServerError"

  /uservouchers:
    get:
      security:
        - bearerAuth: []
      tags:
        - User's Vouchers
      summary: Get all user's vouchers
      responses:
        '200':
          $ref: "#/components/responses/ResponseGetUserVouchers"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '500':
          $ref: "#/components/responses/ServerError"
  
  /claim/{id}:
    post:
      security:
        - bearerAuth: []
      tags:
        - User's Vouchers
      summary: Claim vouchers by voucher id
      parameters:
        - name: id
          in: path
          required: true
          description: id for claim vouchers
          schema:
            type: number
      responses:
        '201':
          $ref: "#/components/responses/ResponseClaimVoucher"
        '400':
          $ref: "#/components/responses/BadRequest"
        '500':
          $ref: "#/components/responses/ServerError" 

  /redeem/{id}:
    post:
      security:
        - bearerAuth: []
      tags:
        - User's Vouchers
      summary: Redeem vouchers by voucher id
      parameters:
        - name: id
          in: path
          required: true
          description: id for redeem vouchers
          schema:
            type: number
      responses:
        '200':
          $ref: "#/components/responses/ResponseRedeemVoucher"
        '400':
          $ref: "#/components/responses/BadRequest"
        '500':
          $ref: "#/components/responses/ServerError" 
                  
  /carts:
    post:
      security:
        - bearerAuth: []
      tags:
        - Carts
      summary: Add item to current login user cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category_id:
                  type: number
                weight:
                  type: number
      responses:
        '201': 
          $ref: "#/components/responses/ResponseCreateCartItem"
        '400':
          $ref: "#/components/responses/BadRequest"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '500':
          $ref: "#/components/responses/ServerError" 
    get:
      security:
        - bearerAuth: []
      tags:
        - Carts
      summary: Get current login user cart items
      responses:
        '200': 
          $ref: "#/components/responses/ResponseGetCart"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '500':
          $ref: "#/components/responses/ServerError"

  /cartitems/{id}:
    put:
      security:
        - bearerAuth: []
      tags:
        - Carts
      summary: Edit cart item by cart item id (current login user)
      parameters:
        - name: id
          in: path
          required: true
          description: id for get specific cart item
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category_id:
                  type: number
                weight:
                  type: number
      responses:
        '200': 
          $ref: "#/components/responses/ResponseEditCartItem"
        '400':
          $ref: "#/components/responses/BadRequest"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '403':
          $ref: "#/components/responses/Forbidden"
        '500':
          $ref: "#/components/responses/ServerError"
    delete:
      security:
        - bearerAuth: []
      tags:
        - Carts
      summary: Delete cart item by cart item id (current login user)
      parameters:
        - name: id
          in: path
          required: true
          description: id for get specific cart item
          schema:
            type: number
      responses:
        '200': 
          $ref: "#/components/responses/ResponseDeleteCartItem"
        '400':
          $ref: "#/components/responses/BadRequest"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '403':
          $ref: "#/components/responses/Forbidden"
        '500':
          $ref: "#/components/responses/ServerError"
  
  /checkoutbypickup:
    post:
      security:
        - bearerAuth: []
      tags:
        - Checkout
      summary: Add checkout by pickup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category_id:
                  type: array
                  items:
                    type: integer
      responses:
        '201': 
          $ref: "#/components/responses/ResponseCreateCheckoutPickup"
        '400':
          $ref: "#/components/responses/BadRequest"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '500':
          $ref: "#/components/responses/ServerError"
        '502':
          $ref: "#/components/responses/BadGateway"
  /checkoutbydropoff:
    post:
      security:
        - bearerAuth: []
      tags:
        - Checkout
      summary: Add checkout by drop off
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                drop_point_id:
                  type: number
                category_id:
                  type: array
                  items:
                    type: integer
      responses:
        '201': 
          $ref: "#/components/responses/ResponseCreateCheckoutDropOff"
        '400':
          $ref: "#/components/responses/BadRequest"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '500':
          $ref: "#/components/responses/ServerError"
        '502':
          $ref: "#/components/responses/BadGateway"
  
  /verification/{id}:
    put:
      security:
        - bearerAuth: []
      tags:
        - Checkout
      summary: Verification checkout (staff only)
      parameters:
        - name: id
          in: path
          required: true
          description: id for verification spesific checkout
          schema:
            type: number
      responses:
        '200': 
          $ref: "#/components/responses/ResponseVerificationCheckout"
        '400':
          $ref: "#/components/responses/BadRequest"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '500':
          $ref: "#/components/responses/ServerError"
        '502':
          $ref: "#/components/responses/BadGateway"
  
  /transactions:
    get:
      security:
        - bearerAuth: []
      tags:
        - Transactions
      summary: Get all transactions
      description: staff can view all transactions, while user can view only her/his transactions
      responses:
        '200': 
          $ref: "#/components/responses/ResponseGetAllTransactions"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '500':
          $ref: "#/components/responses/ServerError"
  
  /transactionsbydroppoint/{id}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Transactions
      summary: Get transaction by drop point id (staff only)
      parameters:
        - name: id
          in: path
          required: true
          description: id for get specific drop point
          schema:
            type: number
      responses:
        '200': 
          $ref: "#/components/responses/ResponseGetAllTransactions"
        '400':
          $ref: "#/components/responses/BadRequest"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '500':
          $ref: "#/components/responses/ServerError"

  /transactionreport/{range}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Transactions
      summary: Get transaction report with range date
      parameters:
        - name: range
          in: path
          required: true
          description: range for get daily, weekly or monthly transactions
          schema:
            type: string
            enum: [daily, weekly, monthly]
      responses:
        '200': 
          $ref: "#/components/responses/ResponseGetAllTransactions"
        '400':
          $ref: "#/components/responses/BadRequest"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '500':
          $ref: "#/components/responses/ServerError"

  /totaltransaction:
    get:
      security:
        - bearerAuth: []
      tags:
        - Transactions
      summary: Get total weight of transactions
      responses:
        '200': 
          $ref: "#/components/responses/ResponseGetTotalTransactions"
        '400':
          $ref: "#/components/responses/BadRequest"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '500':
          $ref: "#/components/responses/ServerError"

  /totaltransaction/{range}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Transactions
      summary: Get total weight of transactions with range date
      parameters:
        - name: range
          in: path
          required: true
          description: range for get daily, weekly or monthly transactions
          schema:
            type: string
            enum: [daily, weekly, monthly]
      responses:
        '200': 
          $ref: "#/components/responses/ResponseGetTotalTransactions"
        '400':
          $ref: "#/components/responses/BadRequest"
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '500':
          $ref: "#/components/responses/ServerError"

  
            
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    StatusOK:
      description: OK 
    BadRequest:
      description: Bad request
    Forbidden: 
      description: Forbidden
    UnauthorizedError:
      description: Invalid or expired jwt
    NotFound:
      description: Status not found
    ServerError:
      description: Internal server error
    BadGateway:
      description: Status bad gateway
    ResponseCreateUser:
      description: Created
      content:
        application/json:
          example:
            data:
              id: 1
              fullname: User
              email: user@gmail.com
              username: user1
              point: 0
              phone_number: 08123456789
              gender: male
              address: jakarta
              role: user
            status: success
    ResponseCreateStaff:
      description: Created
      content:
        application/json:
          example:
            data:
              id: 1
              fullname: Staff
              email: staff1@gmail.com
              username: staff1
              role: staff
              phone_number: 08123456789
              drop_point_id: 1
              drop_point_address: drop point address 1
            status: success
    ResponseEditUser:
      description: OK
      content:
        application/json:
          example:
            data: 
              id: 1
              fullname: User
              email: user@gmail.com
              username: user1
              point: 0
              phone_number: 08123456789
              gender: male
              address: jakarta
              role: user
            status: success
    ResponseLoginUser:
      description: OK
      content:
        application/json:
          example:
            data:
              username: user1
              email: user@gmail.com
              role: user
              token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
            status: success
    ResponseGetAllUsers:
      description: OK
      content:
        application/json:
          example:
            data:
            - id: 1
              fullname: User
              email: user@gmail.com
              username: user1
              point: 0
              phone_number: 08123456789
              gender: male
              address: jakarta
              role: user
            - id: 2
              fullname: User 2
              email: user2@gmail.com
              username: user2
              point: 0
              phone_number: 082187837122
              gender: female
              address: bandung
              role: user
            status: success
    ResponseGetAllStaff:
      description: OK
      content:
        application/json:
          example:
            data:
            - id: 1
              fullname: Staff
              email: staff1@gmail.com
              username: staff1
              role: staff
              phone_number: 08123456789
              drop_point_id: 1
              drop_point_address: drop point address 1
            - id: 1
              fullname: Staff
              email: staff1@gmail.com
              username: staff1
              role: staff
              phone_number: 08123456789
              drop_point_id: 2
              drop_point_address: drop point address 2
            status: success
    ResponseGetProfile:
      description: OK
      content:
        application/json:
          example:
            data:
              id: 1
              fullname: User
              email: user@gmail.com
              username: user1
              point: 0
              phone_number: 08123456789
              gender: male
              address: jakarta
              role: user
            status: success
    ResponseGetAllDropPoint:
      description: OK
      content:
        application/json:
          example:
            data:
            - id: 1
              address: Jakarta
            - id: 2
              address: Bandung
            status: success
    ResponseCreateDropPoint:
      description: Created
      content:
        application/json:
          example:
            data:
              id: 1
              address: Jakarta
            status: success
    ResponseEditDropPoint:
      description: OK
      content:
        application/json:
          example:
            data:
              id: 1
              address: Jakarta
            status: success
    ResponseGetAllCategories:
      description: OK
      content:
        application/json:
          example:
            data:
            - id: 1
              name: Plastik
              point: 10
            - id: 2
              name: Kaca
              point: 20
            status: success
    ResponseCreateCategory:
      description: Created
      content:
        application/json:
          example:
            data:
              id: 1
              name: Plastik
              point: 10
            status: success
    ResponseEditCategory:
      description: OK
      content:
        application/json:
          example:
            data:
              id: 1
              name: Plastik
              point: 10
            status: success
    ResponseGetAllVouchers:
      description: OK
      content:
        application/json:
          example:
            data:
            - id: 1
              name: Voucher 1
              point: 150
            - id: 2
              name: Voucher 2
              point: 200
            status: success
    ResponseCreateVoucher:
      description: Created
      content:
        application/json:
          example:
            data:
              id: 1
              name: Voucher 1
              point: 150
            status: success
    ResponseEditVoucher:
      description: OK
      content:
        application/json:
          example:
            data:
              id: 1
              name: Voucher 1
              point: 150
            status: success
    ResponseGetUserVouchers:
      description: OK
      content:
        application/json:
          example:
            data:
            - id: 1
              user_id: 1
              voucher_id: 1
              voucher_name: Pulsa 10rb
              point: 10
              status: used
            - id: 2
              user_id: 1
              voucher_id: 2
              voucher_name: Pulsa 20rb
              point: 20
              status: available
            status: success
    ResponseGetCart:
      description: OK
      content:
        application/json:
          example:
            data:
            - id: 1
              category_id: 1
              weight: 3
              checkout_id: 0
              cart_user_id: 1
              created_at: "2021-11-04 01:06:18.619"
            - id: 2
              category_id: 2
              weight: 1
              checkout_id: 0
              cart_user_id: 1
              created_at: "2021-11-04 01:06:18.619"
            status: success
    ResponseCreateCartItem:
      description: Created
      content:
        application/json:
          example:
            data:
              id: 1
              category_id: 1
              weight: 3
              checkout_id: 0
              cart_user_id: 1
              created_at: "2021-11-04 01:06:18.619"
            status: success
    ResponseEditCartItem:
      description: Created
      content:
        application/json:
          example:
            data:
              id: 1
              category_id: 1
              weight: 3
              checkout_id: 0
              cart_user_id: 1
              created_at: "2021-11-04 01:06:18.619"
            status: success
    ResponseCreateCheckoutPickup:
      description: Created
      content:
        application/json:
          example:
            data:
              transaction_id: 1
              method: pickup
              drop_point_id: 1
              drop_point_address: Drop point address 1
              distance: 2
              duration: 15
              total_received_points: 13
              categories:
              - category_id: 1
                category_name: Plastik
                point: 3
                weight: 1
                received_points: 3
              - category_id: 2
                category_name: Kaca
                point: 5
                weight: 2
                received_points: 10
            status: success
    ResponseCreateCheckoutDropOff:
      description: Created
      content:
        application/json:
          example:
            data:
              transaction_id: 1
              method: dropoff
              drop_point_id: 1
              drop_point_address: Drop point address 1
              total_received_points: 13
              categories:
              - category_id: 1
                category_name: Plastik
                point: 3
                weight: 1
                received_points: 3
              - category_id: 2
                category_name: Kaca
                point: 5
                weight: 2
                received_points: 10
            status: success
    ResponseVerificationCheckout:
      description: OK
      content:
        application/json:
          example:
            data:
              id: 1
              user_id: 1
              status: 1
              point: 13
              method: dropoff
              drop_point_id: 1
              checkout_id: 1
              created_at: "2021-11-04 01:06:18.619"
              updated_at: "2021-11-04 01:06:18.619"
            status: success
    ResponseGetAllTransactions:
      description: OK
      content:
        application/json:
          example:
            status: success
            data:
            - id: 1
              user_id: 1
              method: dropoff
              drop_point_id: 1
              drop_point_address: drop point address 1
              categories:
              - category_id: 1
                category_name: Plastik
                point: 3
                weight: 1
                received_points: 3
              - category_id: 2
                category_name: Kaca
                point: 5
                weight: 2
                received_points: 10
              created_at: "2021-09-01 20:49:51.428"
              updated_at: "2021-09-01 20:49:51.428"
            - id: 2
              user_id: 1
              method: dropoff
              drop_point_id: 1
              drop_point_address: drop point address 1
              categories:
              - category_id: 1
                category_name: Plastik
                point: 3
                weight: 1
                received_points: 3
              - category_id: 2
                category_name: Kaca
                point: 5
                weight: 2
                received_points: 10
              created_at: "2021-09-01 20:49:51.428"
              updated_at: "2021-09-01 20:49:51.428"
    ResponseGetTotalTransactions:
      description: OK
      content:
        application/json:
          example:
            data:
            - category_id: 1
              category_name: Plastik
              weight: 5
            - category_id: 2
              category_name: Kaca
              weight: 3
            status: success
    ResponseDeleteCategory:
      description: OK
      content:
        application/json:
          example:
            "message": category successfully deleted
    ResponseDeleteVoucher:
      description: OK
      content:
        application/json:
          example:
            "message": voucher successfully deleted
    ResponseDeleteCartItem:
      description: OK
      content:
        application/json:
          example:
            "message": cart item successfully deleted
    ResponseDeleteDropPoint:
      description: OK
      content:
        application/json:
          example:
            "message": drop point successfully deleted
    ResponseClaimVoucher:
      description: Created
      content:
        application/json:
          example:
            data:
              id: 1
              user_id: 1
              voucher_id: 1
              voucher_name: Pulsa 10rb
              point: 10
              status: available
            status: success
    ResponseRedeemVoucher:
      description: OK
      content:
        application/json:
          example:
            data:
              id: 1
              user_id: 1
              voucher_id: 1
              voucher_name: Pulsa 10rb
              point: 10
              status: available
            status: success